owner: sorensd
repo: uptime 

sites:
  - name: Normal Heights
    url: https://normalheights.org/
  - name: MonAmore Boutique
    url: https://monamoreboutique.com/
  - name: Mis Botanitas
    url: https://misbotanitas.com/
  - name: Mariposa Icecream
    url: https://mariposaicecream.com/
  - name: AdamsAvenue.net
    url: https://adamsavenue.net/
  - name: AdamsAvenue.com
    url: https://adamsavenue.com/

status-website:
  # baseUrl: /uptime
  cname: uptime.dary.tech
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: AA Uptime
  introTitle: "**AA Uptime** is powered entirely by [Upptime](https://github.com/upptime/upptime) and GitHub."
  introMessage: Statuses use **real-time** data, deployed by [sorensd](https://github.com/sorensd).
  navbar:
    - title: Status
      href: /
    - title: Adamsavenue
      href: https://adamsavenue.net
